#!/usr/bin/python3
#coding: utf-8

GENERAL_COEFF = "gen"
OFF_COEFF = "off"
DEF_COEFF = "def"
GENERAL_HOME = "home_gen"
OFF_HOME = "home_off"
DEF_HOME = "home_def"
GENERAL_AWAY = "away_gen"
OFF_AWAY = "away_off"
DEF_AWAY = "away_def"

COEFF_VICT_GEN = 2
COEFF_DEF_GEN = -1
COEFF_DRAW_GEN = 1
ADD_MATCHES_GEN = 10
COEFF_SCORED_GEN = 1
COEFF_TAKEN_GEN = -1
ADD_GOALS_GEN = 10

COEFF_VICT_OFF = 3/2
COEFF_DEF_OFF = -1
COEFF_DRAW_OFF = 1/2
COEFF_MATCHES_OFF = 5
ADD_MATCHES_OFF = 5
FIRST_COEFF_OFF = 1
COEFF_SCORED_OFF = 1/3
COEFF_TAKEN_OFF = -1/2
COEFF_GOALS_OFF = 5/2
ADD_GOALS_OFF = 5
SCD_COEFF_OFF = 2/3

COEFF_VICT_DEF = 1
COEFF_DEF_DEF = -4/3
COEFF_DRAW_DEF = 1/3
COEFF_MATCHES_DEF = 5
ADD_MATCHES_DEF = 6
FIRST_COEFF_DEF = 1
COEFF_SCORED_DEF = 1/2
COEFF_TAKEN_DEF = -2
COEFF_GOALS_DEF = 5/2
ADD_GOALS_DEF = 5
SCD_COEFF_DEF = 1

MUTABLE_VARS = {}

## ## New best match output : 73.14 %, January
MUTABLE_VARS["SIMILAR_TEAM_RANGE"] = 88.66667
MUTABLE_VARS["COEFF_DRAW_GEN"] = 5.5
MUTABLE_VARS["COEFF_VICT_GEN"] = 6.4
MUTABLE_VARS["COEFF_GOALS"] = -0.86667
MUTABLE_VARS["COEFF_LEARNING"] = -8.4
MUTABLE_VARS["COEFF_WIN_STREAK"] = 1.3
MUTABLE_VARS["COEFF_DEF_GEN"] = 7.4
MUTABLE_VARS["COEFF_TAKEN_GEN"] = 3.6
MUTABLE_VARS["COEFF_SCORED_GEN"] = 1.2
MUTABLE_VARS["COEFF_VALUE"] = -0.01707
MUTABLE_VARS["COEFF_EXP"] = -0.00355
MUTABLE_VARS["GLOBAL_COEFF"] = 0.6875  


